//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazWeb.WCF_Servicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_Servicio.IRetornarServicios")]
    public interface IRetornarServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetornarServicios/RetornarServicios", ReplyAction="http://tempuri.org/IRetornarServicios/RetornarServiciosResponse")]
        ServiciosObligatorioWCF.DTOServicio[] RetornarServicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetornarServicios/RetornarServicios", ReplyAction="http://tempuri.org/IRetornarServicios/RetornarServiciosResponse")]
        System.Threading.Tasks.Task<ServiciosObligatorioWCF.DTOServicio[]> RetornarServiciosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetornarServicios/RetornarServiciosProveedor", ReplyAction="http://tempuri.org/IRetornarServicios/RetornarServiciosProveedorResponse")]
        ServiciosObligatorioWCF.DTOServicio[] RetornarServiciosProveedor(string unRut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetornarServicios/RetornarServiciosProveedor", ReplyAction="http://tempuri.org/IRetornarServicios/RetornarServiciosProveedorResponse")]
        System.Threading.Tasks.Task<ServiciosObligatorioWCF.DTOServicio[]> RetornarServiciosProveedorAsync(string unRut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRetornarServiciosChannel : InterfazWeb.WCF_Servicio.IRetornarServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetornarServiciosClient : System.ServiceModel.ClientBase<InterfazWeb.WCF_Servicio.IRetornarServicios>, InterfazWeb.WCF_Servicio.IRetornarServicios {
        
        public RetornarServiciosClient() {
        }
        
        public RetornarServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetornarServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetornarServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetornarServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiciosObligatorioWCF.DTOServicio[] RetornarServicios() {
            return base.Channel.RetornarServicios();
        }
        
        public System.Threading.Tasks.Task<ServiciosObligatorioWCF.DTOServicio[]> RetornarServiciosAsync() {
            return base.Channel.RetornarServiciosAsync();
        }
        
        public ServiciosObligatorioWCF.DTOServicio[] RetornarServiciosProveedor(string unRut) {
            return base.Channel.RetornarServiciosProveedor(unRut);
        }
        
        public System.Threading.Tasks.Task<ServiciosObligatorioWCF.DTOServicio[]> RetornarServiciosProveedorAsync(string unRut) {
            return base.Channel.RetornarServiciosProveedorAsync(unRut);
        }
    }
}
