//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppObligatorioP3.OperacionesServiciosRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperacionesServiciosRef.IOperacionesServicios")]
    public interface IOperacionesServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacionesServicios/RetornarServicios", ReplyAction="http://tempuri.org/IOperacionesServicios/RetornarServiciosResponse")]
        ServiciosObligatorioWCF.DTOServicio[] RetornarServicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacionesServicios/RetornarServicios", ReplyAction="http://tempuri.org/IOperacionesServicios/RetornarServiciosResponse")]
        System.Threading.Tasks.Task<ServiciosObligatorioWCF.DTOServicio[]> RetornarServiciosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacionesServicios/RetornarServiciosProveedor", ReplyAction="http://tempuri.org/IOperacionesServicios/RetornarServiciosProveedorResponse")]
        ServiciosObligatorioWCF.DTOServicio[] RetornarServiciosProveedor(string unRut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacionesServicios/RetornarServiciosProveedor", ReplyAction="http://tempuri.org/IOperacionesServicios/RetornarServiciosProveedorResponse")]
        System.Threading.Tasks.Task<ServiciosObligatorioWCF.DTOServicio[]> RetornarServiciosProveedorAsync(string unRut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacionesServicios/AltaProveedor", ReplyAction="http://tempuri.org/IOperacionesServicios/AltaProveedorResponse")]
        bool AltaProveedor(Dominio.Proveedor unProv, Dominio.Usuario unUsu, Dominio.Servicio unServ);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacionesServicios/AltaProveedor", ReplyAction="http://tempuri.org/IOperacionesServicios/AltaProveedorResponse")]
        System.Threading.Tasks.Task<bool> AltaProveedorAsync(Dominio.Proveedor unProv, Dominio.Usuario unUsu, Dominio.Servicio unServ);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacionesServicios/GuardarServiciosEnTxt", ReplyAction="http://tempuri.org/IOperacionesServicios/GuardarServiciosEnTxtResponse")]
        void GuardarServiciosEnTxt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacionesServicios/GuardarServiciosEnTxt", ReplyAction="http://tempuri.org/IOperacionesServicios/GuardarServiciosEnTxtResponse")]
        System.Threading.Tasks.Task GuardarServiciosEnTxtAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperacionesServiciosChannel : ConsoleAppObligatorioP3.OperacionesServiciosRef.IOperacionesServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperacionesServiciosClient : System.ServiceModel.ClientBase<ConsoleAppObligatorioP3.OperacionesServiciosRef.IOperacionesServicios>, ConsoleAppObligatorioP3.OperacionesServiciosRef.IOperacionesServicios {
        
        public OperacionesServiciosClient() {
        }
        
        public OperacionesServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperacionesServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiciosObligatorioWCF.DTOServicio[] RetornarServicios() {
            return base.Channel.RetornarServicios();
        }
        
        public System.Threading.Tasks.Task<ServiciosObligatorioWCF.DTOServicio[]> RetornarServiciosAsync() {
            return base.Channel.RetornarServiciosAsync();
        }
        
        public ServiciosObligatorioWCF.DTOServicio[] RetornarServiciosProveedor(string unRut) {
            return base.Channel.RetornarServiciosProveedor(unRut);
        }
        
        public System.Threading.Tasks.Task<ServiciosObligatorioWCF.DTOServicio[]> RetornarServiciosProveedorAsync(string unRut) {
            return base.Channel.RetornarServiciosProveedorAsync(unRut);
        }
        
        public bool AltaProveedor(Dominio.Proveedor unProv, Dominio.Usuario unUsu, Dominio.Servicio unServ) {
            return base.Channel.AltaProveedor(unProv, unUsu, unServ);
        }
        
        public System.Threading.Tasks.Task<bool> AltaProveedorAsync(Dominio.Proveedor unProv, Dominio.Usuario unUsu, Dominio.Servicio unServ) {
            return base.Channel.AltaProveedorAsync(unProv, unUsu, unServ);
        }
        
        public void GuardarServiciosEnTxt() {
            base.Channel.GuardarServiciosEnTxt();
        }
        
        public System.Threading.Tasks.Task GuardarServiciosEnTxtAsync() {
            return base.Channel.GuardarServiciosEnTxtAsync();
        }
    }
}
